### ISSUE TITLE
B_GWL_CLASS uses incorrect format and subset

### ISSUE THREAD

**Issue by SvenVw** [AgroCares/BedrijfsBodemWaterPlanCalculator#32]
The BBWPC asserts that B_GWL_CLASS uses the subset:
` c('-', 'GtI','GtII','GtIIb','GtIII','GtIIIb','GtIV','GtV','GtVb','GtVI','GtVII','GtVIII'))` 
This is incorrect and should be:
`c(II, IV, IIIb, V, VI, VII, Vb, -, Va, III, VIII, sVI, I, IIb, sVII, IVu, bVII, sV, sVb, bVI, IIIa)`

**Comment by gerardhros** [comment]
this check on B_GWL_CLASS occurs only in bbwp_check_gt where all the prefixes have been deleted. 
is this check recently added to another location resulting in errors?

**Comment by SvenVw** [comment]
https://github.com/AgroCares/BedrijfsBodemWaterPlanCalculator/blob/8bec54127f7c0389863e8bfbdde6c549fefe87b6/R/bbwp_field_properties.R#L62

**Comment by gerardhros** [comment]
solved in hotfix 0.5.7
