### ISSUE TITLE
Function `bbwp()` should only use  B_LU_BRP or B_LU_BBWP and not both

### ISSUE THREAD

**Issue by SvenVw** [AgroCares/BedrijfsBodemWaterPlanCalculator#35]
The function `bbwp` requires among others the arguments  `B_LU_BRP` and `B_LU_BBWP`. As `B_ LU_BBWP` is a property of `B_LU_BRP` it makes no sense to ask both arguments and is a source of potential errors. For example when an user submits the brp code for grassland, but the bbwp category for potatoes. 
Please remove one of the arguments as input for the function to protect users from this potential error

**Comment by gerardhros** [comment]
Fixed in 0.6.0
