### ISSUE TITLE
Need to adjust penalization for high risk indicators

### ISSUE THREAD

**Issue by yuki-nmi** [AgroCares/BedrijfsBodemWaterPlanCalculator#46]
**[Problems]**
While evaluating the BBWP scores for all Dutch agricultural fields (>700,000), it seems that some risk indicators influence the risk index too much. This is because some indicator values have a value 1 or very close to 1 (after conversion formula with ranking), for which very high penalty is imposed. For the the indicator value of 1, penalty (e.g. 1 / (1 - x + 0.2)) is 5. Because of this high penalty value, it blow out the impacts of all other risk indicators!

Note that the BBWP calculation here was done for the whole Netherlands (i.e. the ranking was made not per LSW, but for whole NL).

6 risk indicators use the ranking conversion.  The figure below shows how the raw values (left) are converted to rank-based scores (right):

![image](https://user-images.githubusercontent.com/54851556/189149082-07ac0310-0e70-4919-be47-e5617c2f3c13.png)

For example, ngw_nlv and psw_psg have many high values, as the raw values of A_N_RT and A_P_SG are highly skewed distribution.
I also tried to use log-trransformed values to calculate ranking, but this did not solve the problem because the raw data was not log-normally distributed either.

**[Suggestions for improvement]**

- Make an extra argument in `bbwp_field_properties ` so that the user can choose whether to use penalty or not, as suggested in the PR #47. According to Gerard, the penalty was necessary to differentiate fields in Braband. So, penalty is probably necessary when the BBWP score is calculated on local scale. 

- In future, we should re-consider to change the way to convert raw values to rank-based indicator value. Probably we should not use normal distribution, but the actual distribution of the raw data.

**Comment by gerardhros** [comment]
the feature 'penalty' has been added in branch BBWP-67. Adapting the rank based indicators based on the actual distribution of the data is thereby not yet done. Might be valuable addition.
