### ISSUE TITLE
Set s_er_landscape and s_er_landscape_gold to 1 in BBWPC

### ISSUE THREAD

**Issue by KeesDoolNMI** [AgroCares/BedrijfsBodemWaterPlanCalculator#63]
In the portal s_er_landscape and s_er_landscape_gold should be 1 so it can be visualised in a correct way. In the output from BBWPC they currently has a value of 0 and they are set to 1 in the BBWP-service. This, however, results in inconsistencies in the pdf report, therefore, this should move to the package

**Comment by astridberndsen** [comment]
This issue was solved in version 0.10.18. s_er_landscape and s_er_landscape_gold are now based on the score aims resulting in a value that is always greater than 0.
