### ISSUE TITLE
Output bbwp_field_scores = S_BBWP_* needs transformation 100- S_BBWP to create opportunity index input bbwp+meas_rank

### ISSUE THREAD

**Issue by lauramoria** [AgroCares/BedrijfsBodemWaterPlanCalculator#74]
Oplossing: output bbwp_field_scores = input BBWPC::bbwp_meas_rank = 100- S_BBWP_***
In functie bbwp

**Comment by gerardhros** [comment]
Thanks. This was updated in BBWP version 2.0.0
