### ISSUE TITLE
In bbwp_field_scores opportunity index is calculated by evaluate log waardoor opgave weinig invloed heeft op OPI

### ISSUE THREAD

**Issue by lauramoria** [AgroCares/BedrijfsBodemWaterPlanCalculator#75]
dt[,D_OPI_NGW := OBIC::evaluate_logistic(D_RISK_NGW, b=7, x0=0.5 - cfngw * .1, v=.7)]
formule aanpassen

**Comment by gerardhros** [comment]
thanks for this check and finding. This has been updated in BBWP version 2.0.0.
